### PR TITLE
fix: create s3 bucket for minio

### PR DESCRIPTION
**Pull request by anbraten**
## About

- creates the `lagon` s3 bucket on start when using minio

### CODE REVIEW

**Comment by anbraten** [comment]
cc @akitaSummer

**Review by QuiiBz — APPROVED** [review]
That's smart! Thanks

**Comment by akitaSummer** [comment]
@anbraten Thank you. I was able to successfully access the playground page, but I noticed that because my .env file contains "NEXT_PUBLIC_LAGON_ROOT_DOMAIN=lagon.dev", the function URL is "lagon.dev", and when I perform a deploy, it doesn't reach my server at localhost:4000, resulting in a 404 error on the result page. Is there a good solution to resolve this issue?

**Comment by QuiiBz** [comment]
> I noticed that because my .env file contains "NEXT_PUBLIC_LAGON_ROOT_DOMAIN=lagon.dev", the function URL is "lagon.dev", and when I perform a deploy, it doesn't reach my server at localhost:4000, resulting in a 404 error on the result page. Is there a good solution to resolve this issue?

You can either `curl localhost:4000 -H "Host: yourfunction.lagon.dev"` or add a custom domain to your function named `localhost:4000` (directly in the DB, because the UI only allows domain names).

This is needed because serverless expects a `Host` header with a value being a valid domain. It might be worth documenting this property in the documentation.

**Comment by akitaSummer** [comment]
> > I noticed that because my .env file contains "NEXT_PUBLIC_LAGON_ROOT_DOMAIN=lagon.dev", the function URL is "lagon.dev", and when I perform a deploy, it doesn't reach my server at localhost:4000, resulting in a 404 error on the result page. Is there a good solution to resolve this issue?
> 
> You can either `curl localhost:4000 -H "Host: yourfunction.lagon.dev"` or add a custom domain to your function named `localhost:4000` (directly in the DB, because the UI only allows domain names).
> 
> This is needed because serverless expects a `Host` header with a value being a valid domain. It might be worth documenting this property in the documentation.

Thank you. I had thought of that solution as well, but I don't feel like it's very elegant, so I wanted to ask if there is a more graceful approach.🤣

**Pull request merged**
